declare module 'lucide-react' {
  import type { ComponentType, SVGProps } from 'react';

  export type LucideIcon = ComponentType<SVGProps<SVGSVGElement> & { size?: number | string }>;
  export const Archive: LucideIcon;
  export const AlertTriangle: LucideIcon;
  export const BarChart3: LucideIcon;
  export const BookOpen: LucideIcon;
  export const CalendarCheck: LucideIcon;
  export const CalendarClock: LucideIcon;
  export const CalendarDays: LucideIcon;
  export const Check: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const Clock3: LucideIcon;
  export const CreditCard: LucideIcon;
  export const Download: LucideIcon;
  export const ExternalLink: LucideIcon;
  export const Filter: LucideIcon;
  export const GraduationCap: LucideIcon;
  export const IndianRupee: LucideIcon;
  export const LayoutDashboard: LucideIcon;
  export const Lock: LucideIcon;
  export const LogIn: LucideIcon;
  export const Mail: LucideIcon;
  export const MessageCircle: LucideIcon;
  export const Phone: LucideIcon;
  export const Percent: LucideIcon;
  export const Plus: LucideIcon;
  export const Search: LucideIcon;
  export const Settings: LucideIcon;
  export const StickyNote: LucideIcon;
  export const Trash2: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const Upload: LucideIcon;
  export const Trophy: LucideIcon;
  export const UserPlus: LucideIcon;
  export const User: LucideIcon;
  export const UsersRound: LucideIcon;
  export const WalletCards: LucideIcon;
  export const Zap: LucideIcon;
}
